### ISSUE TITLE
Chapter 7 - Create - Missing a step

### ISSUE THREAD

**Issue by mnagatos101** [PacktPublishing/Microsoft-Semantic-Kernel#1]
In the C# model for the ai search document, you specifically call out that the embedding field is not added like in python...that it will be added later dynamically during upload.  However, i can't find any subsequent mention of this.  When I upload, it says "The request is invalid. Details: Cannot find nested property 'Embedding' on the resource type 'search.documentFields'.".
I will tinker with it more, but wanted to let you know.    

Also, this example constrains me to searching a couple of strings.  I would have liked to have seen a more robust example where I could search all document fields in a more robust index.  In your example, how would you have also included the author field form the json objects?

**Comment by mnagatos101** [comment]
Got it to work by adding the Embedding field via the Azure portal.

**Comment by bsingha27** [comment]
Great to hear that you got it to work @mnagatos101, we're closing this issue! 
If you face any further issues on any chapter, please feel free to open a new one.
